name: Deploy to AWS EC2

on:
  push:
    branches:
      - main  # Trigger this workflow only when pushing to main

jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: SSH into EC2 and deploy
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd webapp-01/ukreact
            echo "📦 Pulling latest code..."
            git pull origin main

            echo "🧩 Installing dependencies..."
            npm install

            echo "🏗️ Building project..."
            npm run build

            echo "🧹 Cleaning old build directory..."
            sudo rm -rf /var/www/vhosts/frontend/build

            echo "📂 Copying new build to Nginx directory..."
            sudo cp -R build /var/www/vhosts/frontend/

            echo "🔄 Restarting Nginx and PM2..."
            sudo systemctl restart nginx
            sudo pm2 restart all

            echo "✅ Deployment complete!"

